#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

fifteen: fifteen.c
	gcc -ggdb -std=c99 -Wall -Werror -o fifteen fifteen.c -I /usr/local/include -L /usr/local/lib -lcs50

clean:
	rm -f *.o a.out core fifteen
