#
# Makefile
#
# Computer Science 50
# Problem Set 5
#

all: recover

whodunit: bmp.h whodunit.c
	gcc -ggdb -std=c99 -Wall -Werror -o recover recover.c 

clean:
	rm -f *.o a.out copy core.* *.jpg recover

